-- fill tables with info about movies

INSERT INTO Movie VALUES ('Movie_Title','Release_Date','Runtime');
INSERT INTO Movie VALUES ('Toy Story','1995-11-22','81');
INSERT INTO Movie VALUES ('A Bugs Life','1998-11-25','96');
INSERT INTO Movie VALUES ('Toy Story 2','1999-11-24','95');
INSERT INTO Movie VALUES ('Monsters Inc','2001-11-02','92');
INSERT INTO Movie VALUES ('Finding Nemo','2003-05-30','100');
INSERT INTO Movie VALUES ('The Incredibles','2004-11-05','115');
INSERT INTO Movie VALUES ('Cars','2006-06-09','116');
INSERT INTO Movie VALUES ('Ratouille','2007-06-29','111');
INSERT INTO Movie VALUES ('WALL-E','2008-06-27','98');
INSERT INTO Movie VALUES ('Up','2009-05-29','96');
INSERT INTO Movie VALUES ('Toy Story 3','2010-06-18','103');
INSERT INTO Movie VALUES ('Cars 2','2011-06-24','106');
INSERT INTO Movie VALUES ('Brave','2012-06-22','93');
INSERT INTO Movie VALUES ('Monsters University','2013-06-21','104');
INSERT INTO Movie VALUES ('Inside Out','2015-06-19','94');
INSERT INTO Movie VALUES ('The Good Dinosaur','2015-11-25','100');
INSERT INTO Movie VALUES ('Finding Dory','2016-06-17','103');
INSERT INTO Movie VALUES ('Cars 3','2017-06-16','102');
INSERT INTO Movie VALUES ('Coco','2017-11-22','109');
INSERT INTO Staff VALUES ('D001','John','Lasseter','Director');
INSERT INTO Staff VALUES ('D002','Pete','Docter','Director');
INSERT INTO Staff VALUES ('D003','Andrew','Stanton','Director');
INSERT INTO Staff VALUES ('D004','Brad','Bird','Director');
INSERT INTO Staff VALUES ('D005','Lee','Unkrich','Director');
INSERT INTO Staff VALUES ('D006','Mark','Andrews','Director');
INSERT INTO Staff VALUES ('D007','Brenda','Chapman','Director');
INSERT INTO Staff VALUES ('D008','Dan','Scanlon','Director');
INSERT INTO Staff VALUES ('D009','Pete','Sohn','Director');
INSERT INTO Staff VALUES ('D010','Brian','Fee','Director');
INSERT INTO Staff VALUES ('P001','Ralph','Guggenheim','Producer');
INSERT INTO Staff VALUES ('P002','Bonnie','Arnold','Producer');
INSERT INTO Staff VALUES ('P003','Darla','Anderson','Producer');
INSERT INTO Staff VALUES ('P004','Kevin','Reher','Producer');
INSERT INTO Staff VALUES ('P005','Karen','Robert Jackson','Producer');
INSERT INTO Staff VALUES ('P006','Helene','Plotkin','Producer');
INSERT INTO Staff VALUES ('P007','Graham','Walters','Producer');
INSERT INTO Staff VALUES ('P008','John','Walker','Producer');
INSERT INTO Staff VALUES ('P009','Brad','Lewis','Producer');
INSERT INTO Staff VALUES ('P010','Jim','Morris','Producer');
INSERT INTO Staff VALUES ('P011','Jonas','Rivera','Producer');
INSERT INTO Staff VALUES ('P012','Denise','Ream','Producer');
INSERT INTO Staff VALUES ('P013','Katherine','Sarafian','Producer');
INSERT INTO Staff VALUES ('P014','Kori','Rae','Producer');
INSERT INTO Staff VALUES ('P015','Lindsey','Collins','Producer');
INSERT INTO Staff VALUES ('P016','Nicole','Paradis Grindle','Producer');
INSERT INTO Staff VALUES ('E001','Robert','Gordon','Editor');
INSERT INTO Staff VALUES ('E002','Edie','Bleiman','Editor');
INSERT INTO Staff VALUES ('E003','David Ian','Salter','Editor');
INSERT INTO Staff VALUES ('E004','Robert','Grahamjones','Editor');
INSERT INTO Staff VALUES ('E005','Jim','Stewart','Editor');
INSERT INTO Staff VALUES ('E006','Stephen','Schaffer','Editor');
INSERT INTO Staff VALUES ('E007','Ken','Schretzmann','Editor');
INSERT INTO Staff VALUES ('E008','Darren','Holmes','Editor');
INSERT INTO Staff VALUES ('E009','Stan','Webb','Editor');
INSERT INTO Staff VALUES ('E010','Kevin','Nolting','Editor');
INSERT INTO Staff VALUES ('E011','Nicholas','Smith','Editor');
INSERT INTO Staff VALUES ('E012','Greg','Snyder','Editor');
INSERT INTO Staff VALUES ('E013','Axel','Geddes','Editor');
INSERT INTO Staff VALUES ('E014','Jason','Hudak','Editor');
INSERT INTO Staff VALUES ('E015','Steve','Bloom','Editor');
INSERT INTO Staff VALUES ('C001','Randy','Newman','Composer');
INSERT INTO Staff VALUES ('C002','Thomas','Newman','Composer');
INSERT INTO Staff VALUES ('C003','Michael','Giacchino','Composer');
INSERT INTO Staff VALUES ('C004','Patrick','Doyle','Composer');
INSERT INTO Staff VALUES ('C005','Mychael','Danna','Composer');
INSERT INTO Staff VALUES ('C006','Jeff','Danna','Composer');
INSERT INTO Staff VALUES ('V001','Tom','Hanks','Voice Actor');
INSERT INTO Staff VALUES ('V002','Tim','Allen','Voice Actor');
INSERT INTO Staff VALUES ('V003','Don','Rickles','Voice Actor');
INSERT INTO Staff VALUES ('V004','Jim','Varney','Voice Actor');
INSERT INTO Staff VALUES ('V005','Wallace','Shawn','Voice Actor');
INSERT INTO Staff VALUES ('V006','John','Ratzenberger','Voice Actor');
INSERT INTO Staff VALUES ('V007','Annie','Potts','Voice Actor');
INSERT INTO Staff VALUES ('V008','John','Morris','Voice Actor');
INSERT INTO Staff VALUES ('V009','Erik','von Detten','Voice Actor');
INSERT INTO Staff VALUES ('V010','Dave','Foley','Voice Actor');
INSERT INTO Staff VALUES ('V011','Kevin','Spacey','Voice Actor');
INSERT INTO Staff VALUES ('V012','Julia','Louis-Dreyfus','Voice Actor');
INSERT INTO Staff VALUES ('V013','Hayden','Panettiere','Voice Actor');
INSERT INTO Staff VALUES ('V014','Phyllis','Diller','Voice Actor');
INSERT INTO Staff VALUES ('V015','Richard','Kind','Voice Actor');
INSERT INTO Staff VALUES ('V016','David','Hyde Pierce','Voice Actor');
INSERT INTO Staff VALUES ('V017','Joe','Ranfit','Voice Actor');
INSERT INTO Staff VALUES ('V018','Denis','Leary','Voice Actor');
INSERT INTO Staff VALUES ('V019','Jonathan','Harris','Voice Actor');
INSERT INTO Staff VALUES ('V020','Joan','Cusack','Voice Actor');
INSERT INTO Staff VALUES ('V021','Kelsey','Grammer','Voice Actor');
INSERT INTO Staff VALUES ('V022','Estelle','Harris','Voice Actor');
INSERT INTO Staff VALUES ('V023','Wayne','Knight','Voice Actor');
INSERT INTO Staff VALUES ('V024','Laurie','Metcalf','Voice Actor');
INSERT INTO Staff VALUES ('V025','Jodi','Benson','Voice Actor');
INSERT INTO Staff VALUES ('V026','Jonathan','Harris','Voice Actor');
INSERT INTO Staff VALUES ('V027','Jeff','Pidgeon','Voice Actor');
INSERT INTO Staff VALUES ('V028','John','Goodman','Voice Actor');
INSERT INTO Staff VALUES ('V029','Billy','Crystal','Voice Actor');
INSERT INTO Staff VALUES ('V030','Mary','Gibbs','Voice Actor');
INSERT INTO Staff VALUES ('V031','Steve','Buscemi','Voice Actor');
INSERT INTO Staff VALUES ('V032','James','Coburn','Voice Actor');
INSERT INTO Staff VALUES ('V033','Jennifer','Tilly','Voice Actor');
INSERT INTO Staff VALUES ('V034','Bob','Peterson','Voice Actor');
INSERT INTO Staff VALUES ('V035','Frank','Oz','Voice Actor');
INSERT INTO Staff VALUES ('V036','Dan','Gerson','Voice Actor');
INSERT INTO Staff VALUES ('V037','Steve','Susskind','Voice Actor');
INSERT INTO Staff VALUES ('V038','Phil','Proctor','Voice Actor');
INSERT INTO Staff VALUES ('V039','Albert','Brooks','Voice Actor');
INSERT INTO Staff VALUES ('V040','Ellen','DeGeneres','Voice Actor');
INSERT INTO Staff VALUES ('V041','Alexander','Gould','Voice Actor');
INSERT INTO Staff VALUES ('V042','Willem','Dafoe','Voice Actor');
INSERT INTO Staff VALUES ('V043','Brad','Garrett','Voice Actor');
INSERT INTO Staff VALUES ('V044','Allison','Janney','Voice Actor');
INSERT INTO Staff VALUES ('V045','Stephen','Root','Voice Actor');
INSERT INTO Staff VALUES ('V046','Austin','Pendleton','Voice Actor');
INSERT INTO Staff VALUES ('V047','Vicki','Lewis','Voice Actor');
INSERT INTO Staff VALUES ('V048','Geoffrey','Rush','Voice Actor');
INSERT INTO Staff VALUES ('V049','Craig','Nelson','Voice Actor');
INSERT INTO Staff VALUES ('V050','Holly','Hunter','Voice Actor');
INSERT INTO Staff VALUES ('V051','Sarah','Vowell','Voice Actor');
INSERT INTO Staff VALUES ('V052','Spencer','Fox','Voice Actor');
INSERT INTO Staff VALUES ('V053','Eli','Fucile','Voice Actor');
INSERT INTO Staff VALUES ('V054','Jason','Lee','Voice Actor');
INSERT INTO Staff VALUES ('V055','Samuel','Jackson','Voice Actor');
INSERT INTO Staff VALUES ('V056','Elizabeth','Pena','Voice Actor');
INSERT INTO Staff VALUES ('V057','Bud','Luckey','Voice Actor');
INSERT INTO Staff VALUES ('V058','Michael','Bird','Voice Actor');
INSERT INTO Staff VALUES ('V059','Owen','Wilson','Voice Actor');
INSERT INTO Staff VALUES ('V060','Paul','Newman','Voice Actor');
INSERT INTO Staff VALUES ('V061','Bonnie','Hunt','Voice Actor');
INSERT INTO Staff VALUES ('V062','Larry','the Cable Guy','Voice Actor');
INSERT INTO Staff VALUES ('V063','Tony','Shalhoub','Voice Actor');
INSERT INTO Staff VALUES ('V064','Cheech','Marin','Voice Actor');
INSERT INTO Staff VALUES ('V065','Michael','Wallis','Voice Actor');
INSERT INTO Staff VALUES ('V066','George','Carlin','Voice Actor');
INSERT INTO Staff VALUES ('V067','Paul','Dooley','Voice Actor');
INSERT INTO Staff VALUES ('V068','Jenifer','Lewis','Voice Actor');
INSERT INTO Staff VALUES ('V069','Richard','Petty','Voice Actor');
INSERT INTO Staff VALUES ('V070','Patton','Oswalt','Voice Actor');
INSERT INTO Staff VALUES ('V071','Ian','Holm','Voice Actor');
INSERT INTO Staff VALUES ('V072','Lou','Romano','Voice Actor');
INSERT INTO Staff VALUES ('V073','Janeane','Garofalo','Voice Actor');
INSERT INTO Staff VALUES ('V074','Brian','Dennehy','Voice Actor');
INSERT INTO Staff VALUES ('V075','Peter','O'Toole','Voice Actor');
INSERT INTO Staff VALUES ('V076','Will','Arnett','Voice Actor');
INSERT INTO Staff VALUES ('V077','James','Remar','Voice Actor');
INSERT INTO Staff VALUES ('V078','Teddy','Newton','Voice Actor');
INSERT INTO Staff VALUES ('V079','Ben','Burtt','Voice Actor');
INSERT INTO Staff VALUES ('V080','Elissa','Knight','Voice Actor');
INSERT INTO Staff VALUES ('V081','Jeff','Garlin','Voice Actor');
INSERT INTO Staff VALUES ('V082','Fred','Willard','Voice Actor');
INSERT INTO Staff VALUES ('V083','Kathy','Najimy','Voice Actor');
INSERT INTO Staff VALUES ('V084','Sigourney','Weaver','Voice Actor');
INSERT INTO Staff VALUES ('V085','Ed','Asner','Voice Actor');
INSERT INTO Staff VALUES ('V086','Jordan','Nagai','Voice Actor');
INSERT INTO Staff VALUES ('V087','Christopher','Plummer','Voice Actor');
INSERT INTO Staff VALUES ('V088','Delroy','Lindo','Voice Actor');
INSERT INTO Staff VALUES ('V089','Jerome','Ranfit','Voice Actor');
INSERT INTO Staff VALUES ('V090','Ned','Beatty','Voice Actor');
INSERT INTO Staff VALUES ('V091','Michael','Keaton','Voice Actor');
INSERT INTO Staff VALUES ('V092','Emily','Hahn','Voice Actor');
INSERT INTO Staff VALUES ('V093','Timothy','Dalton','Voice Actor');
INSERT INTO Staff VALUES ('V094','Kristen','Schaal','Voice Actor');
INSERT INTO Staff VALUES ('V095','Jeff','Garlin','Voice Actor');
INSERT INTO Staff VALUES ('V096','Whoopi','Goldberg','Voice Actor');
INSERT INTO Staff VALUES ('V097','Michael','Caine','Voice Actor');
INSERT INTO Staff VALUES ('V098','Emily','Mortimer','Voice Actor');
INSERT INTO Staff VALUES ('V099','John','Turturro','Voice Actor');
INSERT INTO Staff VALUES ('V100','Eddie','Izzard','Voice Actor');
INSERT INTO Staff VALUES ('V101','Thomas','Kretschmann','Voice Actor');
INSERT INTO Staff VALUES ('V102','Joe','Mantegna','Voice Actor');
INSERT INTO Staff VALUES ('V103','Bruce','Cambell','Voice Actor');
INSERT INTO Staff VALUES ('V104','Darrell','Waltrip','Voice Actor');
INSERT INTO Staff VALUES ('V105','Guido','Quaroni','Voice Actor');
INSERT INTO Staff VALUES ('V106','Brent','Musburger','Voice Actor');
INSERT INTO Staff VALUES ('V107','Colin','Cowherd','Voice Actor');
INSERT INTO Staff VALUES ('V108','Jason','Isaacs','Voice Actor');
INSERT INTO Staff VALUES ('V109','David','Hobbs','Voice Actor');
INSERT INTO Staff VALUES ('V110','Stanley','Townsend','Voice Actor');
INSERT INTO Staff VALUES ('V111','Lloyd','Sherr','Voice Actor');
INSERT INTO Staff VALUES ('V112','Sig','Hansen','Voice Actor');
INSERT INTO Staff VALUES ('V113','Franco','Nero','Voice Actor');
INSERT INTO Staff VALUES ('V114','Vanessa','Redgrave','Voice Actor');
INSERT INTO Staff VALUES ('V115','Kelly','Macdonald','Voice Actor');
INSERT INTO Staff VALUES ('V116','Emma','Thompson','Voice Actor');
INSERT INTO Staff VALUES ('V117','Billy','Connolly','Voice Actor');
INSERT INTO Staff VALUES ('V118','Julie','Walters','Voice Actor');
INSERT INTO Staff VALUES ('V119','Robbie','Coltrane','Voice Actor');
INSERT INTO Staff VALUES ('V120','Kevin','McKidd','Voice Actor');
INSERT INTO Staff VALUES ('V121','Craig','Ferguson','Voice Actor');
INSERT INTO Staff VALUES ('V122','Steve','Purcell','Voice Actor');
INSERT INTO Staff VALUES ('V123','Helen','Mirren','Voice Actor');
INSERT INTO Staff VALUES ('V124','Joel','Murray','Voice Actor');
INSERT INTO Staff VALUES ('V125','Sean','Hayes','Voice Actor');
INSERT INTO Staff VALUES ('V126','Charlie','Day','Voice Actor');
INSERT INTO Staff VALUES ('V127','Alfred','Molina','Voice Actor');
INSERT INTO Staff VALUES ('V128','Tyler','Labine','Voice Actor');
INSERT INTO Staff VALUES ('V129','Nathan','Fillion','Voice Actor');
INSERT INTO Staff VALUES ('V130','Aubrey','Plaza','Voice Actor');
INSERT INTO Staff VALUES ('V131','Bobby','Moynihan','Voice Actor');
INSERT INTO Staff VALUES ('V132','Julia','Sweeney','Voice Actor');
INSERT INTO Staff VALUES ('V133','John','Krasinski','Voice Actor');
INSERT INTO Staff VALUES ('V134','Bill','Hader','Voice Actor');
INSERT INTO Staff VALUES ('V135','Beth','Behrs','Voice Actor');

INSERT INTO Staff VALUES ('Toy Story','D001');
INSERT INTO Staff VALUES ('Toy Story','P001');
INSERT INTO Staff VALUES ('Toy Story','P002');
INSERT INTO Staff VALUES ('Toy Story','E001');
INSERT INTO Staff VALUES ('Toy Story','C001');
INSERT INTO Staff VALUES ('Toy Story','V001');
INSERT INTO Staff VALUES ('Toy Story','V002');
INSERT INTO Staff VALUES ('Toy Story','V003');
INSERT INTO Staff VALUES ('Toy Story','V004');
INSERT INTO Staff VALUES ('Toy Story','V005');
INSERT INTO Staff VALUES ('Toy Story','V006');
INSERT INTO Staff VALUES ('Toy Story','V007');
INSERT INTO Staff VALUES ('Toy Story','V008');
INSERT INTO Staff VALUES ('Toy Story','V009');
INSERT INTO Staff VALUES ('A Bugs Life','D001');
INSERT INTO Staff VALUES ('A Bugs Life','P003');
INSERT INTO Staff VALUES ('A Bugs Life','P004');
INSERT INTO Staff VALUES ('A Bugs Life','C001');
INSERT INTO Staff VALUES ('A Bugs Life','V010');
INSERT INTO Staff VALUES ('A Bugs Life','V011');
INSERT INTO Staff VALUES ('A Bugs Life','V012');
INSERT INTO Staff VALUES ('A Bugs Life','V013');
INSERT INTO Staff VALUES ('A Bugs Life','V014');
INSERT INTO Staff VALUES ('A Bugs Life','V015');
INSERT INTO Staff VALUES ('A Bugs Life','V016');
INSERT INTO Staff VALUES ('A Bugs Life','V017');
INSERT INTO Staff VALUES ('A Bugs Life','V018');
INSERT INTO Staff VALUES ('A Bugs Life','V019');
INSERT INTO Staff VALUES ('Toy Story 2','D001');
INSERT INTO Staff VALUES ('Toy Story 2','P005');
INSERT INTO Staff VALUES ('Toy Story 2','P006');
INSERT INTO Staff VALUES ('Toy Story 2','V001');
INSERT INTO Staff VALUES ('Toy Story 2','V002');
INSERT INTO Staff VALUES ('Toy Story 2','V003');
INSERT INTO Staff VALUES ('Toy Story 2','V004');
INSERT INTO Staff VALUES ('Toy Story 2','V005');
INSERT INTO Staff VALUES ('Toy Story 2','V006');
INSERT INTO Staff VALUES ('Toy Story 2','V007');
INSERT INTO Staff VALUES ('Toy Story 2','V008');
INSERT INTO Staff VALUES ('Toy Story 2','V020');
INSERT INTO Staff VALUES ('Toy Story 2','V021');
INSERT INTO Staff VALUES ('Toy Story 2','V022');
INSERT INTO Staff VALUES ('Toy Story 2','V023');
INSERT INTO Staff VALUES ('Toy Story 2','V024');
INSERT INTO Staff VALUES ('Toy Story 2','V025');
INSERT INTO Staff VALUES ('Toy Story 2','V026');
INSERT INTO Staff VALUES ('Toy Story 2','V027');
INSERT INTO Staff VALUES ('Monsters Inc','D002');
INSERT INTO Staff VALUES ('Monsters Inc','P003');
INSERT INTO Staff VALUES ('Monsters Inc','E004');
INSERT INTO Staff VALUES ('Monsters Inc','E005');
INSERT INTO Staff VALUES ('Monsters Inc','C001');
INSERT INTO Staff VALUES ('Monsters Inc','V028');
INSERT INTO Staff VALUES ('Monsters Inc','V029');
INSERT INTO Staff VALUES ('Monsters Inc','V030');
INSERT INTO Staff VALUES ('Monsters Inc','V031');
INSERT INTO Staff VALUES ('Monsters Inc','V032');
INSERT INTO Staff VALUES ('Monsters Inc','V033');
INSERT INTO Staff VALUES ('Monsters Inc','V034');
INSERT INTO Staff VALUES ('Monsters Inc','V035');
INSERT INTO Staff VALUES ('Monsters Inc','V036');
INSERT INTO Staff VALUES ('Monsters Inc','V037');
INSERT INTO Staff VALUES ('Monsters Inc','V038');
INSERT INTO Staff VALUES ('Monsters Inc','V006');
INSERT INTO Staff VALUES ('Monsters Inc','V017');
INSERT INTO Staff VALUES ('Monsters Inc','V027');
INSERT INTO Staff VALUES ('Finding Nemo','D003');
INSERT INTO Staff VALUES ('Finding Nemo','P007');
INSERT INTO Staff VALUES ('Finding Nemo','E003');
INSERT INTO Staff VALUES ('Finding Nemo','C002');
INSERT INTO Staff VALUES ('Finding Nemo','V039');
INSERT INTO Staff VALUES ('Finding Nemo','V040');
INSERT INTO Staff VALUES ('Finding Nemo','V041');
INSERT INTO Staff VALUES ('Finding Nemo','V042');
INSERT INTO Staff VALUES ('Finding Nemo','V043');
INSERT INTO Staff VALUES ('Finding Nemo','V044');
INSERT INTO Staff VALUES ('Finding Nemo','V045');
INSERT INTO Staff VALUES ('Finding Nemo','V046');
INSERT INTO Staff VALUES ('Finding Nemo','V047');
INSERT INTO Staff VALUES ('Finding Nemo','V048');
INSERT INTO Staff VALUES ('The Incredibles','D004');
INSERT INTO Staff VALUES ('The Incredibles','P008');
INSERT INTO Staff VALUES ('The Incredibles','E006');
INSERT INTO Staff VALUES ('The Incredibles','C003');
INSERT INTO Staff VALUES ('The Incredibles','V049');
INSERT INTO Staff VALUES ('The Incredibles','V050');
INSERT INTO Staff VALUES ('The Incredibles','V051');
INSERT INTO Staff VALUES ('The Incredibles','V052');
INSERT INTO Staff VALUES ('The Incredibles','V053');
INSERT INTO Staff VALUES ('The Incredibles','V054');
INSERT INTO Staff VALUES ('The Incredibles','V055');
INSERT INTO Staff VALUES ('The Incredibles','V056');
INSERT INTO Staff VALUES ('The Incredibles','V057');
INSERT INTO Staff VALUES ('The Incredibles','V058');
INSERT INTO Staff VALUES ('Cars','D001');
INSERT INTO Staff VALUES ('Cars','P003');
INSERT INTO Staff VALUES ('Cars','E007');
INSERT INTO Staff VALUES ('Cars','C001');
INSERT INTO Staff VALUES ('Cars','V059');
INSERT INTO Staff VALUES ('Cars','V060');
INSERT INTO Staff VALUES ('Cars','V061');
INSERT INTO Staff VALUES ('Cars','V062');
INSERT INTO Staff VALUES ('Cars','V063');
INSERT INTO Staff VALUES ('Cars','V064');
INSERT INTO Staff VALUES ('Cars','V065');
INSERT INTO Staff VALUES ('Cars','V066');
INSERT INTO Staff VALUES ('Cars','V067');
INSERT INTO Staff VALUES ('Cars','V068');
INSERT INTO Staff VALUES ('Cars','V069');
INSERT INTO Staff VALUES ('Ratatouille','D004');
INSERT INTO Staff VALUES ('Ratatouille','P009');
INSERT INTO Staff VALUES ('Ratatouille','E008');
INSERT INTO Staff VALUES ('Ratatouille','E009');
INSERT INTO Staff VALUES ('Ratatouille','C003');
INSERT INTO Staff VALUES ('Ratatouille','V070');
INSERT INTO Staff VALUES ('Ratatouille','V071');
INSERT INTO Staff VALUES ('Ratatouille','V072');
INSERT INTO Staff VALUES ('Ratatouille','V073');
INSERT INTO Staff VALUES ('Ratatouille','V074');
INSERT INTO Staff VALUES ('Ratatouille','V075');
INSERT INTO Staff VALUES ('Ratatouille','V076');
INSERT INTO Staff VALUES ('Ratatouille','V077');
INSERT INTO Staff VALUES ('Ratatouille','V078');
INSERT INTO Staff VALUES ('Ratatouille','V043');
INSERT INTO Staff VALUES ('Ratatouille','V006');
INSERT INTO Staff VALUES ('WALL-E','D003');
INSERT INTO Staff VALUES ('WALL-E','P010');
INSERT INTO Staff VALUES ('WALL-E','E006');
INSERT INTO Staff VALUES ('WALL-E','C002');
INSERT INTO Staff VALUES ('WALL-E','V079');
INSERT INTO Staff VALUES ('WALL-E','V080');
INSERT INTO Staff VALUES ('WALL-E','V081');
INSERT INTO Staff VALUES ('WALL-E','V082');
INSERT INTO Staff VALUES ('WALL-E','V083');
INSERT INTO Staff VALUES ('WALL-E','V084');
INSERT INTO Staff VALUES ('WALL-E','V006');
INSERT INTO Staff VALUES ('Up','D002');
INSERT INTO Staff VALUES ('Up','P011');
INSERT INTO Staff VALUES ('Up','E010');
INSERT INTO Staff VALUES ('Up','C003');
INSERT INTO Staff VALUES ('Up','V085');
INSERT INTO Staff VALUES ('Up','V086');
INSERT INTO Staff VALUES ('Up','V087');
INSERT INTO Staff VALUES ('Up','V088');
INSERT INTO Staff VALUES ('Up','V089');
INSERT INTO Staff VALUES ('Up','V006');
INSERT INTO Staff VALUES ('Toy Story 3','D005');
INSERT INTO Staff VALUES ('Toy Story 3','P003');
INSERT INTO Staff VALUES ('Toy Story 3','E007');
INSERT INTO Staff VALUES ('Toy Story 3','C001');
INSERT INTO Staff VALUES ('Toy Story 3','V001');
INSERT INTO Staff VALUES ('Toy Story 3','V002');
INSERT INTO Staff VALUES ('Toy Story 3','V003');
INSERT INTO Staff VALUES ('Toy Story 3','V020');
INSERT INTO Staff VALUES ('Toy Story 3','V008');
INSERT INTO Staff VALUES ('Toy Story 3','V005');
INSERT INTO Staff VALUES ('Toy Story 3','V006');
INSERT INTO Staff VALUES ('Toy Story 3','V022');
INSERT INTO Staff VALUES ('Toy Story 3','V025');
INSERT INTO Staff VALUES ('Toy Story 3','V027');
INSERT INTO Staff VALUES ('Toy Story 3','V061');
INSERT INTO Staff VALUES ('Toy Story 3','V078');
INSERT INTO Staff VALUES ('Toy Story 3','V009');
INSERT INTO Staff VALUES ('Toy Story 3','V090');
INSERT INTO Staff VALUES ('Toy Story 3','V091');
INSERT INTO Staff VALUES ('Toy Story 3','V092');
INSERT INTO Staff VALUES ('Toy Story 3','V093');
INSERT INTO Staff VALUES ('Toy Story 3','V094');
INSERT INTO Staff VALUES ('Toy Story 3','V095');
INSERT INTO Staff VALUES ('Toy Story 3','V096');
INSERT INTO Staff VALUES ('Cars 2','D001');
INSERT INTO Staff VALUES ('Cars 2','P012');
INSERT INTO Staff VALUES ('Cars 2','E006');
INSERT INTO Staff VALUES ('Cars 2','C003');
INSERT INTO Staff VALUES ('Cars 2','V059');
INSERT INTO Staff VALUES ('Cars 2','V061');
INSERT INTO Staff VALUES ('Cars 2','V062');
INSERT INTO Staff VALUES ('Cars 2','V063');
INSERT INTO Staff VALUES ('Cars 2','V064');
INSERT INTO Staff VALUES ('Cars 2','V065');
INSERT INTO Staff VALUES ('Cars 2','V067');
INSERT INTO Staff VALUES ('Cars 2','V068');
INSERT INTO Staff VALUES ('Cars 2','V006');
INSERT INTO Staff VALUES ('Cars 2','V097');
INSERT INTO Staff VALUES ('Cars 2','V098');
INSERT INTO Staff VALUES ('Cars 2','V099');
INSERT INTO Staff VALUES ('Cars 2','V100');
INSERT INTO Staff VALUES ('Cars 2','V101');
INSERT INTO Staff VALUES ('Cars 2','V102');
INSERT INTO Staff VALUES ('Cars 2','V103');
INSERT INTO Staff VALUES ('Cars 2','V104');
INSERT INTO Staff VALUES ('Cars 2','V105');
INSERT INTO Staff VALUES ('Cars 2','V106');
INSERT INTO Staff VALUES ('Cars 2','V107');
INSERT INTO Staff VALUES ('Cars 2','V108');
INSERT INTO Staff VALUES ('Cars 2','V109');
INSERT INTO Staff VALUES ('Cars 2','V110');
INSERT INTO Staff VALUES ('Cars 2','V111');
INSERT INTO Staff VALUES ('Cars 2','V112');
INSERT INTO Staff VALUES ('Cars 2','V113');
INSERT INTO Staff VALUES ('Cars 2','V114');
INSERT INTO Staff VALUES ('Brave','D006');
INSERT INTO Staff VALUES ('Brave','D007');
INSERT INTO Staff VALUES ('Brave','P013');
INSERT INTO Staff VALUES ('Brave','E011');
INSERT INTO Staff VALUES ('Brave','C004');
INSERT INTO Staff VALUES ('Brave','V115');
INSERT INTO Staff VALUES ('Brave','V116');
INSERT INTO Staff VALUES ('Brave','V117');
INSERT INTO Staff VALUES ('Brave','V118');
INSERT INTO Staff VALUES ('Brave','V119');
INSERT INTO Staff VALUES ('Brave','V120');
INSERT INTO Staff VALUES ('Brave','V121');
INSERT INTO Staff VALUES ('Brave','V122');
INSERT INTO Staff VALUES ('Brave','V006');
INSERT INTO Staff VALUES ('Monsters University','D008');
INSERT INTO Staff VALUES ('Monsters University','P014');
INSERT INTO Staff VALUES ('Monsters University','E012');
INSERT INTO Staff VALUES ('Monsters University','C001');
INSERT INTO Staff VALUES ('Monsters University','V028');
INSERT INTO Staff VALUES ('Monsters University','V029');
INSERT INTO Staff VALUES ('Monsters University','V031');
INSERT INTO Staff VALUES ('Monsters University','V006');
INSERT INTO Staff VALUES ('Monsters University','V034');
INSERT INTO Staff VALUES ('Monsters University','V123');
INSERT INTO Staff VALUES ('Monsters University','V124');
INSERT INTO Staff VALUES ('Monsters University','V125');
INSERT INTO Staff VALUES ('Monsters University','V126');
INSERT INTO Staff VALUES ('Monsters University','V127');
INSERT INTO Staff VALUES ('Monsters University','V128');
INSERT INTO Staff VALUES ('Monsters University','V129');
INSERT INTO Staff VALUES ('Monsters University','V130');
INSERT INTO Staff VALUES ('Monsters University','V131');
INSERT INTO Staff VALUES ('Monsters University','V132');
INSERT INTO Staff VALUES ('Monsters University','V133');
INSERT INTO Staff VALUES ('Monsters University','V134');
INSERT INTO Staff VALUES ('Monsters University','V135');

INSERT INTO Budget VALUES ('B001','Toy Story','30000000');
INSERT INTO Budget VALUES ('B002','A Bugs Life','45000000');
INSERT INTO Budget VALUES ('B003','Toy Story 2','90000000');
INSERT INTO Budget VALUES ('B004','Monsters Inc','115000000');
INSERT INTO Budget VALUES ('B005','Finding Nemo','94000000');
INSERT INTO Budget VALUES ('B006','The Incredibles','92000000');
INSERT INTO Budget VALUES ('B007','Cars','70000000');
INSERT INTO Budget VALUES ('B008','Ratouille','150000000');
INSERT INTO Budget VALUES ('B009','WALL-E','180000000');
INSERT INTO Budget VALUES ('B010','Up','175000000');
INSERT INTO Budget VALUES ('B011','Toy Story 3','200000000');
INSERT INTO Budget VALUES ('B012','Cars 2','200000000');
INSERT INTO Budget VALUES ('B013','Brave','185000000');
INSERT INTO Budget VALUES ('B014','Monsters University','200000000');
INSERT INTO Budget VALUES ('B015','Inside Out','175000000');
INSERT INTO Budget VALUES ('B016','The Good Dinosaur','187500000');
INSERT INTO Budget VALUES ('B017','Finding Dory','200000000');
INSERT INTO Budget VALUES ('B018','Cars 3','175000000');
INSERT INTO Budget VALUES ('B019','Coco','175000000');
INSERT INTO Budget VALUES ('B020','Incredibles 2','200000000');

INSERT INTO Income VALUES ('I001','Toy Story','29140617','191796233','364545516');
INSERT INTO Income VALUES ('I002','A Bugs Life','291121','162798565','363095319');
INSERT INTO Income VALUES ('I003','Toy Story 2','300163','245852179','511358276');
INSERT INTO Income VALUES ('I004','Monsters Inc','62577067','289423425','559757719');
INSERT INTO Income VALUES ('I005','Finding Nemo','70251710','380529370','936429370');
INSERT INTO Income VALUES ('I006','The Incredibles','70467623','261441092','614726725');
INSERT INTO Income VALUES ('I007','Cars','60119509','244082982','461651246');
INSERT INTO Income VALUES ('I008','Ratouille','47027395','206445695','625549695');
INSERT INTO Income VALUES ('I009','WALL-E','63087526','223808164','532508025');
INSERT INTO Income VALUES ('I010','Up','110307189','293004164','731463377');
INSERT INTO Income VALUES ('I011','Toy Story 3','66135507','415004880','1068879522');
INSERT INTO Income VALUES ('I012','Cars 2','66323594','191450875','560155383');
INSERT INTO Income VALUES ('I013','Brave','82429469','237282182','554606532');
INSERT INTO Income VALUES ('I014','Monsters University','90440272','268488329','743588329');
INSERT INTO Income VALUES ('I015','Inside Out','39155217','356461711','854235992');
INSERT INTO Income VALUES ('I016','The Good Dinosaur','135060273','123087120','333771037');
INSERT INTO Income VALUES ('I017','Finding Dory','53688680','486295561','1021215193');
INSERT INTO Income VALUES ('I018','Cars 3','53688680','152901115','383549151');
INSERT INTO Income VALUES ('I019','Coco','50802605','209726015','798020225');
INSERT INTO Income VALUES ('I020','Incredibles 2','182687905','608581744','1242532436');

INSERT INTO soundtrack VALUES ('001',	'Youve Got a Friend in Me',	'2:04');
INSERT INTO soundtrack VALUES ('002',	'Strange Thinks',	'3:18');
INSERT INTO soundtrack VALUES ('003',	'I Will Go Sailing No More',	'2:57');
INSERT INTO soundtrack VALUES ('004',	'The Time of Your Life',	'3:14');
INSERT INTO soundtrack VALUES ('005',	'Woodys Roundup',	'1:53');
INSERT INTO soundtrack VALUES ('006',	'When She Loved Me',	'3:04');
INSERT INTO soundtrack VALUES ('007',	'If I Didnt Have You',	'3:41');
INSERT INTO soundtrack VALUES ('008',	'Beyond the Sea',	'3:12');
INSERT INTO soundtrack VALUES ('009',	'Life Is a Highway',	'4:37');
INSERT INTO soundtrack VALUES ('010',	'Real Gone',	'3:22');
INSERT INTO soundtrack VALUES ('011',	'Our Town',	'4:07');
INSERT INTO soundtrack VALUES ('012',	'Behind the Clouds',	'4:09');
INSERT INTO soundtrack VALUES ('013',	'Find Yourself',	'4:11');
INSERT INTO soundtrack VALUES ('014',	'Sh-Boom',	'2:26');
INSERT INTO soundtrack VALUES ('015',	'Route 66',	'3:25');
INSERT INTO soundtrack VALUES ('016',	'My Heart Would Know',	'2:27');

INSERT INTO multiple_songs VALUES ('Toy Story', '001');
INSERT INTO multiple_songs VALUES ('Toy Story', '002');
INSERT INTO multiple_songs VALUES ('Toy Story', '003');
INSERT INTO multiple_songs VALUES ('A Bugs Life', '004');
INSERT INTO multiple_songs VALUES ('Toy Story 2', '005');
INSERT INTO multiple_songs VALUES ('Toy Story 2', '006');
INSERT INTO multiple_songs VALUES ('Toy Story 2', '001');
INSERT INTO multiple_songs VALUES ('Monsters Inc.', '007');
INSERT INTO multiple_songs VALUES ('Finding Nemo', '008');
INSERT INTO multiple_songs VALUES ('Cars', '009');
INSERT INTO multiple_songs VALUES ('Cars', '010');
INSERT INTO multiple_songs VALUES ('Cars', '011');
INSERT INTO multiple_songs VALUES ('Cars', '012');
INSERT INTO multiple_songs VALUES ('Cars', '013');
INSERT INTO multiple_songs VALUES ('Cars', '014');
INSERT INTO multiple_songs VALUES ('Cars', '015');
INSERT INTO multiple_songs VALUES ('Cars', '016');

INSERT INTO soundtrack_singer VALUES ('001',	'Randy Newman');
INSERT INTO soundtrack_singer VALUES ('002',	'Randy Newman');
INSERT INTO soundtrack_singer VALUES ('003',	'Randy Newman');
INSERT INTO soundtrack_singer VALUES ('004',	'Randy Newman');
INSERT INTO soundtrack_singer VALUES ('005',	'Riders in the Sky');
INSERT INTO soundtrack_singer VALUES ('006',	'Sarah McLachlan');
INSERT INTO soundtrack_singer VALUES ('007',	'Billy Crystal');
INSERT INTO soundtrack_singer VALUES ('007',	'John Goodman');
INSERT INTO soundtrack_singer VALUES ('008',	'Robbie Williams');
INSERT INTO soundtrack_singer VALUES ('009',	'Rascal Flatts');
INSERT INTO soundtrack_singer VALUES ('010',	'Sheryl Crow');
INSERT INTO soundtrack_singer VALUES ('011',	'James Taylor');
INSERT INTO soundtrack_singer VALUES ('012',	'Brad Paisley');
INSERT INTO soundtrack_singer VALUES ('013',	'Brad Paisley');
INSERT INTO soundtrack_singer VALUES ('014',	'The Chords');
INSERT INTO soundtrack_singer VALUES ('015',	'John Mayer');
INSERT INTO soundtrack_singer VALUES ('016',	'Hank Williams');

INSERT INTO soundtrack VALUES ('017',	'Le Festin','2:52');
INSERT INTO soundtrack VALUES ('018',	'Define Dancing','2:29');
INSERT INTO soundtrack VALUES ('019',	'Married Life',	'4:13');
INSERT INTO soundtrack VALUES ('020',	'We Belong Together','4:03');
INSERT INTO soundtrack VALUES ('021',	'You Might Think','3:06');
INSERT INTO soundtrack VALUES ('022',	'Touch the Sky','2:32');

INSERT INTO multiple_songs VALUES ('Ratatouille', '017');
INSERT INTO multiple_songs VALUES ('WALL-E', '018');
INSERT INTO multiple_songs VALUES ('Up', '019');
INSERT INTO multiple_songs VALUES ('Toy Story 3', '020');
INSERT INTO multiple_songs VALUES ('Cars 2', '021');
INSERT INTO multiple_songs VALUES ('Brave', '022');

INSERT INTO soundtrack_singer VALUES ('017', 'Camile');
INSERT INTO soundtrack_singer VALUES ('018', 'Thomas Newman');
INSERT INTO soundtrack_singer VALUES ('019', 'Michael Giacchino');
INSERT INTO soundtrack_singer VALUES ('020', 'Randy Newman');
INSERT INTO soundtrack_singer VALUES ('021', 'Weezer');
INSERT INTO soundtrack_singer VALUES ('022', 'Julie Fowlis');

INSERT INTO soundtrack VALUES('024','Monsters University',	'1:35');
INSERT INTO soundtrack VALUES('025', 'Sweet Emotion',	'4:34');
INSERT INTO soundtrack VALUES('026','Crystals',	'4:04');
INSERT INTO soundtrack VALUES('027', 'Unforgettable',	'3:18');
INSERT INTO soundtrack VALUES('028','Run That Race',	'2:44');
INSERT INTO soundtrack VALUES('029','Ride',	'5:03');
INSERT INTO soundtrack VALUES('030','Kings Highway',	'3:07');
INSERT INTO soundtrack VALUES('031','Glory Days',	'4:07');
INSERT INTO soundtrack VALUES('032','Drive My Car',	'2:42');
INSERT INTO soundtrack VALUES('033','Freeway of Love',	'4:33');
INSERT INTO soundtrack VALUES('034','Rememer Me',	'1:49');
INSERT INTO soundtrack VALUES('035','Everyone Knows Juanita',	'1:15');
INSERT INTO soundtrack VALUES('036','La Llorona',	'2:46');
INSERT INTO soundtrack VALUES('037','Proud Corazon',	'2:04');
INSERT INTO soundtrack VALUES('038','Pow! Pow! Pow!',	'1:31');

INSERT INTO multiple_songs VALUES('Monsters University', '024');
INSERT INTO multiple_songs VALUES('Inside Out', '025');
INSERT INTO multiple_songs VALUES('The Good Dinosaur', '026');
INSERT INTO multiple_songs VALUES('Finding Dory', '027');
INSERT INTO multiple_songs VALUES('Cars 3', '028');
INSERT INTO multiple_songs VALUES('Cars 3', '029');
INSERT INTO multiple_songs VALUES('Cars 3', '030');
INSERT INTO multiple_songs VALUES('Cars 3', '031');
INSERT INTO multiple_songs VALUES('Cars 3', '032');
INSERT INTO multiple_songs VALUES('Cars 3', '033');
INSERT INTO multiple_songs VALUES('Cars 3', '034');
INSERT INTO multiple_songs VALUES('Coco', '035');
INSERT INTO multiple_songs VALUES('Coco', '036');
INSERT INTO multiple_songs VALUES('Coco', '037');
INSERT INTO multiple_songs VALUES('Incredibles 2', '038');

INSERT INTO soundtrack_singer VALUES('024',	'Randy Newman');
INSERT INTO soundtrack_singer VALUES('025',	'Aerosmith');
INSERT INTO soundtrack_singer VALUES('026',	'Of Monsters and Men');
INSERT INTO soundtrack_singer VALUES('027',	'Sia');
INSERT INTO soundtrack_singer VALUES('028',	'Dan Auerbach');
INSERT INTO soundtrack_singer VALUES('029',	'ZZ Ward');
INSERT INTO soundtrack_singer VALUES('030',	'James Bay');
INSERT INTO soundtrack_singer VALUES('031',	'Andra Day');
INSERT INTO soundtrack_singer VALUES('032',	'Jorge Blanco');
INSERT INTO soundtrack_singer VALUES('034',	'Lea DeLaria');
INSERT INTO soundtrack_singer VALUES('035',	'Gael Garcia Bernal');
INSERT INTO soundtrack_singer VALUES('036',	'Alanna Ubach');
INSERT INTO soundtrack_singer VALUES('037',	'Anthony Gonzalez');
INSERT INTO soundtrack_singer VALUES('038',	'DCappella');

INSERT INTO Critics VALUES ('C001','Rotten Tomatoes');
INSERT INTO Critics VALUES ('C002','IMDb');
INSERT INTO Critics VALUES ('C003','Metacritic');

INSERT INTO Movie_Review VALUES ('Toy Story','C001','10');
INSERT INTO Movie_Review VALUES ('Toy Story','C002','8.3');
INSERT INTO Movie_Review VALUES ('Toy Story','C003','9.5');
INSERT INTO Movie_Review VALUES ('A Bugs Life','C001','9.2');
INSERT INTO Movie_Review VALUES ('A Bugs Life','C002','7.2');
INSERT INTO Movie_Review VALUES ('A Bugs Life','C003','7.7');
INSERT INTO Movie_Review VALUES ('Toy Story 2','C001','10');
INSERT INTO Movie_Review VALUES ('Toy Story 2','C002','7.9');
INSERT INTO Movie_Review VALUES ('Toy Story 2','C003','8.8');
INSERT INTO Movie_Review VALUES ('Monsters Inc','C001','9.6');
INSERT INTO Movie_Review VALUES ('Monsters Inc','C002','8.1');
INSERT INTO Movie_Review VALUES ('Monsters Inc','C003','7.8');
INSERT INTO Movie_Review VALUES ('Finding Nemo','C001','9.9');
INSERT INTO Movie_Review VALUES ('Finding Nemo','C002','8.1');
INSERT INTO Movie_Review VALUES ('Finding Nemo','C003','9');
INSERT INTO Movie_Review VALUES ('The Incredibles','C001','9.7');
INSERT INTO Movie_Review VALUES ('The Incredibles','C002','8');
INSERT INTO Movie_Review VALUES ('The Incredibles','C003','9');
INSERT INTO Movie_Review VALUES ('Cars','C001','7.4');
INSERT INTO Movie_Review VALUES ('Cars','C002','7.1');
INSERT INTO Movie_Review VALUES ('Cars','C003','7.3');
INSERT INTO Movie_Review VALUES ('Ratouille','C001','9.6');
INSERT INTO Movie_Review VALUES ('Ratouille','C002','8');
INSERT INTO Movie_Review VALUES ('Ratouille','C003','9.6');
INSERT INTO Movie_Review VALUES ('WALL-E','C001','9.6');
INSERT INTO Movie_Review VALUES ('WALL-E','C002','8.4');
INSERT INTO Movie_Review VALUES ('WALL-E','C003','9.5');
INSERT INTO Movie_Review VALUES ('Up','C001','9.8');
INSERT INTO Movie_Review VALUES ('Up','C002','8.3');
INSERT INTO Movie_Review VALUES ('Up','C003','9.2');
INSERT INTO Movie_Review VALUES ('Toy Story 3','C001','9.8');
INSERT INTO Movie_Review VALUES ('Toy Story 3','C002','8.3');
INSERT INTO Movie_Review VALUES ('Toy Story 3','C003','9.2');
INSERT INTO Movie_Review VALUES ('Cars 2','C001','3.8');
INSERT INTO Movie_Review VALUES ('Cars 2','C002','6.2');
INSERT INTO Movie_Review VALUES ('Cars 2','C003','5.7');
INSERT INTO Movie_Review VALUES ('Brave','C001','7.9');
INSERT INTO Movie_Review VALUES ('Brave','C002','7.1');
INSERT INTO Movie_Review VALUES ('Brave','C003','6.9');
INSERT INTO Movie_Review VALUES ('Monsters University','C001','7.9');
INSERT INTO Movie_Review VALUES ('Monsters University','C002','7.3');
INSERT INTO Movie_Review VALUES ('Monsters University','C003','6.5');
INSERT INTO Movie_Review VALUES ('Inside Out','C001','9.8');
INSERT INTO Movie_Review VALUES ('Inside Out','C002','8.2');
INSERT INTO Movie_Review VALUES ('Inside Out','C003','9.4');
INSERT INTO Movie_Review VALUES ('The Good Dinosaur','C001','7.6');
INSERT INTO Movie_Review VALUES ('The Good Dinosaur','C002','6.7');
INSERT INTO Movie_Review VALUES ('The Good Dinosaur','C003','6.6');
INSERT INTO Movie_Review VALUES ('Finding Dory','C001','9.4');
INSERT INTO Movie_Review VALUES ('Finding Dory','C002','7.3');
INSERT INTO Movie_Review VALUES ('Finding Dory','C003','7.7');
INSERT INTO Movie_Review VALUES ('Cars 3','C001','6.9');
INSERT INTO Movie_Review VALUES ('Cars 3','C002','6.8');
INSERT INTO Movie_Review VALUES ('Cars 3','C003','5.9');
INSERT INTO Movie_Review VALUES ('Coco','C001','9.7');
INSERT INTO Movie_Review VALUES ('Coco','C002','8.4');
INSERT INTO Movie_Review VALUES ('Coco','C003','8.1');
INSERT INTO Movie_Review VALUES ('Incredibles 2','C001','9.3');
INSERT INTO Movie_Review VALUES ('Incredibles 2','C002','7.7');
INSERT INTO Movie_Review VALUES ('Incredibles 2','C003','8');

INSERT INTO award VALUES ('A001',	'Toy Story',	'Best Family Feature',	'1996',	'Young Artist Awards');
INSERT INTO award VALUES ('A002',	'Toy Story',	'Best Picture',	'2016',	'20/20 Awards');
INSERT INTO award VALUES ('A003',	'Toy Story',	'Top Box Office Films',	'1996',	'ASCAP Awards');
INSERT INTO award VALUES ('A004',	'Toy Story',	'Best Original Score',	'1996',	'CFCA Awards');
INSERT INTO award VALUES ('A005',	'Toy Story',	'Best Animation',	'1995',	'LAFCA Awards');
INSERT INTO award VALUES ('A006',	'A Bugs Life',	'Favorite Animated Family Movie',	'1999',	'Blockbuster Entertainment Awards');
INSERT INTO award VALUES ('A007',	'A Bugs Life',	'Best Instrumental Composition',	'2000',	'Grammy Awards');
INSERT INTO award VALUES ('A008',	'A Bugs Life',	'Best Animation',	'1998',	'LAFCA Awards');
INSERT INTO award VALUES ('A009',	'A Bugs Life',	'Best Original Score',	'1999',	'CFCA Awards');
INSERT INTO award VALUES ('A010',	'A Bugs Life',	'Best Sound Editing',	'1999',	'Motion Picture Sound Editors');
INSERT INTO award VALUES ('A011',	'Toy Story 2',	'Best Motion Picture',	'2000',	'Golden Globes');
INSERT INTO award VALUES ('A012',	'Toy Story 2',	'Best Song Written for a Motion Picture',	'2001',	'Grammy Awards');
INSERT INTO award VALUES ('A013',	'Toy Story 2',	'Top Box Office Films',	'2000',	'ASCAP Awards');
INSERT INTO award VALUES ('A014',	'Toy Story 2',	'Best Animated Film',	'1999',	'KCFCC Awards');
INSERT INTO award VALUES ('A015',	'Toy Story 2',	'Best Motion Picture',	'2000',	'Satellite Awards');
INSERT INTO award VALUES ('A016',	'Monsters Inc.',	'Best Music',	'2002',	'Academy Awards');
INSERT INTO award VALUES ('A017',	'Monsters Inc.',	'Best Feature Film',	'2002',	'BAFTA Awards');
INSERT INTO award VALUES ('A018',	'Monsters Inc.',	'Best Song Written for a Motion Picture',	'2003',	'Grammy Awards');
INSERT INTO award VALUES ('A019',	'Monsters Inc.',	'Top Box Office Films',	'2002',	'ASCAP Awards');
INSERT INTO award VALUES ('A020',	'Monsters Inc.',	'Best Youth DVD',	'2003',	'Satellite Awards');
INSERT INTO award VALUES ('A021',	'Monsters Inc.',	'Best Original Song Written for a Film',	'2002',	'World Soundtrack Awards');
INSERT INTO award VALUES ('A022',	'Finding Nemo',	'Best Animated Feature',	'2004',	'Academy Awards');
INSERT INTO award VALUES ('A023',	'Finding Nemo',	'Favorite Movie',	'2004',	'Kids Choice Awards');
INSERT INTO award VALUES ('A024',	'Finding Nemo',	'Favorite Voice from an Animated Movie',	'2004',	'Kids Choice Awards');
INSERT INTO award VALUES ('A025',	'Finding Nemo',	'Best Performance in a Voice-Over Role',	'2004',	'Young Artist Awards');
INSERT INTO award VALUES ('A026',	'The Incredibles',	'Best Animated Feature Film of the Year',	'2005',	'Academy Awards');
INSERT INTO award VALUES ('A027',	'The Incredibles',	'Best Feature Film',	'2005',	'BAFTA Awards');
INSERT INTO award VALUES ('A028',	'The Incredibles',	'Favorite Movie',	'2005',	'Kids Choice Awards');
INSERT INTO award VALUES ('A029',	'The Incredibles',	'Best Instrumental Arrangement',	'2006',	'Grammy Awards');
INSERT INTO award VALUES ('A030',	'The Incredibles',	'Best Dramatic Presentation',	'2005',	'Hugo Awards');
INSERT INTO award VALUES ('A031',	'Cars',	'Best Animated Film',	'2007',	'Golden Globes');
INSERT INTO award VALUES ('A032',	'Cars',	'Top Box Office Films',	'2007',	'ASCAP Awards');
INSERT INTO award VALUES ('A033',	'Cars',	'Best Song Written for a Motion Picture',	'2007',	'Grammy Awards');
INSERT INTO award VALUES ('A034',	'Cars',	'Favorite Family Movie',	'2007',	'Peoples Choice Awards');
INSERT INTO award VALUES ('A035',	'Cars',	'Animation of the Year',	'2006',	'Hollywood Film Awards');
INSERT INTO award VALUES ('A036',	'Ratatouille','Best Animated Film','2008','Golden Globe');
INSERT INTO award VALUES ('A037',	'Ratatouille','Best Animated Feature Film of the Year','2008','Academy Award');
INSERT INTO award VALUES ('A038',	'Ratatouille','Best Animated Film','2008','BAFTA Awards');
INSERT INTO award VALUES ('A039',	'Ratatouille','Best Writing',	'2008','Academy of Science Fiction, Fantasy & Horror');
INSERT INTO award VALUES ('A040',	'Ratatouille','Movie of the Year','2008','AFI Awards');
INSERT INTO award VALUES ('A041',	'WALL-E','Best Animated Feature Film of the Year','2009','Academy Award');
INSERT INTO award VALUES ('A042',	'WALL-E','Best Animated Film','2009','Golden Globe');
INSERT INTO award VALUES ('A043',	'WALL-E','Best Animated Film','2009','BAFTA Awards');
INSERT INTO award VALUES ('A044',	'WALL-E','Best Feature  Film','2009','BAFTA Awards');
INSERT INTO award VALUES ('A045',	'Up','Best Animated Feature Film of the Year','2010','Academy Award');
INSERT INTO award VALUES ('A046',	'Up','Best Achievement in Music for Motion Pictures','2010','Academy Award');
INSERT INTO award VALUES ('A047',	'Up','Best Original Score - Motion Picture','2010',	'Golden Globe');
INSERT INTO award VALUES ('A048',	'Up','Best Animated Film','2010','BAFTA Awards');
INSERT INTO award VALUES ('A049',	'Toy Story 3','Best Animated Feature Film of the Year','2011','Academy Award');
INSERT INTO award VALUES ('A050',	'Toy Story 3','Best Achievement in Music for Motion Pictures','2011','Academy Award');
INSERT INTO award VALUES ('A051',	'Toy Story 3','Best Animated Film',	'202011','Golden Globe');
INSERT INTO award VALUES ('A052',	'Toy Story 3','Best Animated Film','2011','BAFTA Awards');
INSERT INTO award VALUES ('A053',	'Cars 2','Top Box Office Films','2012','ASCAP');
INSERT INTO award VALUES ('A054',	'Brave','Best Animated Feature','2013',	'Academy Award');
INSERT INTO award VALUES ('A055',	'Brave','Best Animated Feature Film','2013','Golden Globe');
INSERT INTO award VALUES ('A056',	'Brave','Best Animated Film','2013','BAFTA Awards');
INSERT INTO award VALUES ('A057',   'Brave','Best Animated Female','2013', 'Alliance of Women Film Journalists');
INSERT INTO award VALUES('A058',	'Monsters University',	'Top Box Office Films',	'2014',	'ASCAP Awards');
INSERT INTO award VALUES('A059',	'Monsters University',	'Best Female Vocal Performace',	'2014',	'Behind the Voice Actors Award');
INSERT INTO award VALUES('A060',	'Monsters University',	'Most Original Trailer',	'2013',	'Golden Trailer Awards');
INSERT INTO award VALUES('A061',	'Monsters University',	'Best Animation/ Family TV Spot',	'2013',	'Golden Trailer Awards');
INSERT INTO award VALUES('A062',	'Inside Out',	'Best Animated Feature Film of the Year',	'2016',	'Academy Awards');
INSERT INTO award VALUES('A063',	'Inside Out',	'Best Motion Picture - Animated',	'2016',	'Golden Globes');
INSERT INTO award VALUES('A064',	'Inside Out',	'Best Animated Film',	'2016',	'BAFTA Awards');
INSERT INTO award VALUES('A065',	'Inside Out',	'Best Stereography',	'2016',	'3D Creative Arts Awards');
INSERT INTO award VALUES('A066',	'Inside Out',	'Best 3D Picture - Animated',	'2016',	'3D Creative Arts Awards');
INSERT INTO award VALUES('A067',	'Inside Out',	'Best Animated Film',	'2016',	'Academy of Science Fiction');
INSERT INTO award VALUES('A068',	'Inside Out',	'Movie of the Year',	'2016',	'AFI Awards');
INSERT INTO award VALUES('A069',	'The Good Dinosaur',	'Film Music',	'2016',	'BMI Film & TV Awards');
INSERT INTO award VALUES('A070',	'The Good Dinosaur',	'Outstanding Achievement in Animated Effects',	'2016',	'Annie Awards');
INSERT INTO award VALUES('A071',	'Finding Dory',	'Best Animated Film',	'2017',	'Academy of Science Fiction');
INSERT INTO award VALUES('A072',	'Finding Dory',	'Outstanding Achievement in Sound Mixing',	'2017',	'Cinema Audio Society');
INSERT INTO award VALUES('A073',	'Finding Dory',	'Favorite Animated Movie',	'2017',	'KidsChoice Awards');
INSERT INTO award VALUES('A074',	'Finding Dory',	'Favorite Voice from an Animated Movie',	'2017',	'Kids Choice Awards');
INSERT INTO award VALUES('A075',	'Finding Dory',	'SQUAD',	'2017',	'Kids Choice Awards');
INSERT INTO award VALUES('A076',	'Finding Dory',	'Most Wanted Pet',	'2017',	'Kids Choice Awards');
INSERT INTO award VALUES('A077',	'Cars 3', 'NULL', 'NULL', 'NULL');	
INSERT INTO award VALUES('A078',	'Coco',	'Best Animated Feature Film', '2018',	'Academy Awards');
INSERT INTO award VALUES('A079',	'Coco',	'Best Achievement in Music',	'2018',	'Academy Awards');
INSERT INTO award VALUES('A080',	'Coco',	'Best Motion Picture - Animated', '2018',	'Golden Globes');
INSERT INTO award VALUES('A081',	'Coco',	'Best Animated Feature Film',	'2018',	'BAFTA Awards');
INSERT INTO award VALUES('A082',	'Coco',	'Best Music',	'2018',	'Academy of Science Fiction');
INSERT INTO award VALUES('A083',	'Coco',	'Best Animated Film',	'2018',	'Academy of Science Fiction');
INSERT INTO award VALUES('A084',	'Incredibles 2',	'Best Summer Blockbuster', '2018', 	'Golden Trailer Awards');
INSERT INTO award VALUES('A085',	'Incredibles 2',	'Favorite Family Movie',	'2018',	'Peoples Choice Awards');
INSERT INTO award VALUES('A086',	'Incredibles 2',	'Choice Summer Movie',	'2018',	'Teen Choice Awards');
